# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Andrew O'Harney
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           Andrew O'Harney
  url:            


github:
  repo:           https://github.com/andrew0harney
